import { useState } from 'react'
import { ArrowUpRight, Check, Mail, MapPin, Phone } from 'lucide-react'
import { Link } from 'react-router-dom'
import { achievements, projects, skills, timeline } from '../data/content'
import { BulletList, ContactForm, PageIntro, ProjectCard, Reveal } from '../components/UI'
import profile from '../assets/derajkumar-profile.jpeg'

export function About() { return <div className="container inner-page"><PageIntro eyebrow="About" title={<>Engineering across full<br /><em>stack, AI and security.</em></>} body="A motivated Computer Science Engineering student driven by software development, full-stack development, cybersecurity research, and AI-powered problem solving — building systems that translate into real-world impact across environment, health, and safety." /><div className="about-layout"><div className="about-photo"><img src={profile} alt="Portrait of Derajkumar S" /></div><div><p className="large-copy">I'm a final-year B.E. Computer Science Engineering student at MNM Jain Engineering College, Anna University, Chennai.</p><p className="body-copy">My work sits at the intersection of software and full-stack product engineering, applied AI/ML, and cybersecurity. I build complete systems — interfaces, APIs and data layers — with an emphasis on clarity and performance.</p><p className="body-copy">On the AI side I've worked with computer vision pipelines, LSTM forecasting and satellite data analysis. On the security side I focus on network security, vulnerability assessment and forensics.</p><div className="about-mini-grid"><article><strong>CTF competitor</strong><span>Web exploitation, forensics and reverse-engineering challenges.</span></article><article><strong>OSINT researcher</strong><span>Footprint mapping, verification workflows and clear reporting.</span></article></div></div></div><div className="about-band"><span>Based in <strong>Chennai, Tamil Nadu</strong></span><span>Currently <strong>open to opportunities</strong></span><span>Interested in <strong>AI · security · web</strong></span></div></div> }

function TimelinePage({ kind }: { kind: 'education' | 'experience' }) { const entries = timeline[kind]; return <div className="container inner-page"><PageIntro eyebrow={kind === 'education' ? 'Education' : 'Experience'} title={kind === 'education' ? <>Learning the<br /><em>long game.</em></> : <>Industry exposure in<br /><em>infrastructure & security.</em></>} body={kind === 'education' ? 'The classrooms, problems, and questions shaping my approach to engineering.' : 'Hands-on time inside a manufacturing enterprise, where uptime and network integrity are non-negotiable.'} /><div className="timeline">{entries.map((entry, index) => <Reveal delay={index * .1} key={entry.title}><article className="timeline-item"><span className="timeline-dot" /><div className="timeline-period">{entry.period}</div><div><h3>{entry.title}</h3><p className="timeline-org">{entry.org}</p><p>{entry.detail}</p></div></article></Reveal>)}</div></div> }
export function Education() { return <TimelinePage kind="education" /> }
export function Experience() { return <TimelinePage kind="experience" /> }

export function Skills() { return <div className="container inner-page"><PageIntro eyebrow="Skills" title={<>A stack built for building<br /><em>and breaking.</em></>} body="Tooling and techniques I use daily across product engineering, machine learning and security work." /><div className="skill-list">{skills.map((skill, index) => <Reveal delay={index * .08} key={skill.group}><article className="skill-row"><div className="skill-head"><h3>{skill.group}</h3><span>{skill.level}%</span></div><div className="progress"><span style={{ width: `${skill.level}%` }} /></div><div className="tag-row">{skill.items.map((item) => <span key={item}>{item}</span>)}</div></article></Reveal>)}</div></div> }

export function Services() { const services = [{ number: '01', title: 'Full-stack builds', text: 'Responsive, thoughtfully structured web apps that stay understandable as they grow.', list: ['React & TypeScript', 'APIs & data flows', 'Performance-minded UI'] }, { number: '02', title: 'AI prototypes', text: 'From a messy question to a testable model and an interface people can actually use.', list: ['Computer vision', 'Forecasting & data', 'Proof-of-concept builds'] }, { number: '03', title: 'Security analysis', text: 'A careful look at the boundaries, assumptions, and weak spots inside a system.', list: ['Network visibility', 'Vulnerability review', 'Forensics & CTF'] }]; return <div className="container inner-page"><PageIntro eyebrow="What I can help with" title={<>Good work starts<br /><em>with good questions.</em></>} body="Whether you need a working prototype, a clearer system, or a second pair of eyes on security, I bring curiosity and structure to the table." /><div className="service-grid">{services.map((service, index) => <Reveal delay={index * .1} key={service.number}><article className="service-card"><span className="card-number">{service.number}</span><h2>{service.title}</h2><p>{service.text}</p><BulletList items={service.list} /><Link className="text-link" to="/contact">Discuss a project <ArrowUpRight size={15} /></Link></article></Reveal>)}</div></div> }

export function Projects() { const [filter, setFilter] = useState('All'); const visible = filter === 'All' ? projects : projects.filter((project) => project.category === filter); return <div className="container inner-page"><PageIntro eyebrow="Selected work" title={<>Built to be<br /><em>put to use.</em></>} body="A selection of projects across AI, security, and the web. Some are shipped, some are still asking better questions." /><div className="filter-row" role="tablist">{['All', 'AI', 'Security', 'Web'].map((item) => <button className={filter === item ? 'filter active' : 'filter'} key={item} onClick={() => setFilter(item)} role="tab" aria-selected={filter === item}>{item}</button>)}</div><div className="projects-grid">{visible.map((project, index) => <Reveal delay={index * .06} key={project.name}><ProjectCard project={project} /></Reveal>)}</div></div> }

export function Achievements() { return <div className="container inner-page"><PageIntro eyebrow="Milestones" title={<>Small wins.<br /><em>Useful momentum.</em></>} body="The moments that gave an idea enough energy to keep moving." /><div className="achievement-grid">{achievements.map((item, index) => <Reveal delay={index * .08} key={item.number}><article className="achievement-card"><span>{item.number}</span><h2>{item.title}</h2><p>{item.detail}</p></article></Reveal>)}</div></div> }

export function Contact() { return <div className="container inner-page contact-page"><PageIntro eyebrow="Get in touch" title={<>Let's start with<br /><em>a conversation.</em></>} body="Have a project, internship, or research idea in mind? Send a note and I will get back to you." /><div className="contact-layout"><ContactForm /><aside className="contact-aside"><p className="eyebrow">Direct lines</p><a href="mailto:deraj.srinivasan@outlook.com"><Mail size={18} /> deraj.srinivasan@outlook.com</a><a href="tel:+919940721203"><Phone size={18} /> +91 99407 21203</a><span><MapPin size={18} /> Chennai, Tamil Nadu, India</span><div className="contact-note"><Check size={17} /><p>I usually reply within a couple of days. Good questions welcome.</p></div></aside></div></div> }
